### A Nbdev script file ###
### Autogenerated file. Don't modify. ###

#export
using TOML


#export
begin
"""
> getsetting(f:: AbstractString, key:: AbstractString) --> get the items related to a key from the Project.toml file
"""
function getsetting(f:: AbstractString, key:: AbstractString)
	a = TOML.parsefile(f)
	return a[key]
end

"""
> getsettings(f:: AbstractString, keys:: AbstractString) --> get the items related to the keys from the Project.toml file
"""
function getsettings(f:: AbstractString, keys)
	res = TOML.parsefile(f)
	for key in keys
		#"$res"
		res = res[key]
	end
	return res
end
end


#export
"""
> strip --> Helper fucntion to replace a substring y in a string x with blank.
"""
strip=(x::String,y) -> replace(x, y=>"")


